<h1 align="left"> Desafio de Engenharia de Qualidade de Software </h1>

<p align="left">
<img loading="lazy" src="https://img.shields.io/badge/status-finalizado-blue"/>
</p>

<h2 align="left"> Descri√ß√£o do projeto </h2>

<p align="left">
  Este projeto possui como objetivo realizar a leitura de um arquivo de log que cont√©m mensagens de erros de fun√ß√µes de um determinado equipamento, agrupando estas mensagens por cada fun√ß√£o e imprimindo essa informa√ß√£o em um relat√≥rio para o usu√°rio. 
</p>

<p align="left">
  Para garantir a confiabilidade do c√≥digo, tamb√©m foi desenvolvido um script que cont√©m fun√ß√µes de testes, que verificam se os erros apresentados no relat√≥rio est√£o condizentes com o conte√∫do do arquivo de log.
</p>

# :hammer: Funcionalidades do projeto

- `Funcionalidade 1`: Foi desenvolvido uma API que recebe como parametro o nome do arquivo de log a ser lido. Essa API retorna os erros agrupados em um json, e caso n√£o encontre o arquivo informado, retornar√° um json com erro.

  ![evidencia_retorno_json](https://github.com/lvsantosdev/teste_log/assets/105672045/ae209837-de8d-4617-9ad4-dd1d6acd0380)

  ![evidencia_retorno_json_erro](https://github.com/lvsantosdev/teste_log/assets/105672045/b706cdd5-70e8-4c78-b9a5-ffa562219bfe)

- `Funcionalidade 2`: Imprimir em um relat√≥rio para o usu√°rio os erros do arquivo de log agrupados por fun√ß√£o, mostrando tamb√©m a quantidade que ocorrem. O arquivo main.py se comunica com a API e imprime os erros agrupados por fun√ß√£o. Caso ocorra algum erro na API, a informa√ß√£o ser√° passada para o usu√°rio

  ![evidencia_relatorio](https://github.com/lvsantosdev/teste_log/assets/105672045/5901f098-c94f-4318-8e79-8ce49ae6399f)

  ![evidencia_relatorio_erro](https://github.com/lvsantosdev/teste_log/assets/105672045/ef3d0fe3-4198-4261-a382-92a69f521e0a)

- `Funcionalidade 3`: O arquivo testes.py cont√©m fun√ß√µes de testes desenvolvidas para valida√ß√£o do json retornado pela API, tanto no caso de sucesso nos testes, quanto nos casos de erro. Tamb√©m √© poss√≠vel validar se a mensagem de erro est√° de acordo com o documentado. Em ambos os casos, quando o retorno conter True significa que o teste passou, enquanto False significa que o teste foi recusado.
  - `Funcionalidade 3a`: A fun√ß√£o teste_total_erros(nome_arquivo_log, retorno_esperado) recebe como input o nome do arquivo a ser lido e a quantidade total de erros que deve conter nesse arquivo.
  
    ![evidencia_teste_total](https://github.com/lvsantosdev/teste_log/assets/105672045/96ca84bc-546d-4dc8-8429-3931fe894699)
  
  - `Funcionalidade 3b`: A fun√ß√£o teste_quantidade_erros_funcao(nome_arquivo_log, funcao_esperada, retorno_esperado) recebe como input o nome do arquivo a ser lido, o nome da fun√ß√£o e a quantidade total de erros esperada para essa fun√ß√£o.

    ![evidencia_teste_fun_total](https://github.com/lvsantosdev/teste_log/assets/105672045/43198704-79c6-4c4b-834c-6c4297fc0d99)
    
  - `Funcionalidade 3c`: A fun√ß√£o teste_tipo_qtd_erros_funcao(nome_arquivo_log, funcao_esperada, erro_esperado, retorno_esperado) recebe como input o nome do arquivo a ser lido, o nome da fun√ß√£o, a mensagem de erro da fun√ß√£o e a quantidade total de erros esperada para essa mensagem nessa respectiva fun√ß√£o.

    ![evidencia_teste_fun_msg_total](https://github.com/lvsantosdev/teste_log/assets/105672045/e3a6d5d0-54cf-4089-a346-1c82a64db199)

<p align="left">
  Para facilitar na manuten√ß√£o do c√≥digo, o arquivo util.py cont√©m fun√ß√µes de utilidade para o projeto, e o arquivo init.py cont√©m parametros utilizados para realizar substring no arquivo de log no momento de separar as mensagens de erro e fun√ß√£o.
</p>

# üìÅ Informa√ß√µes complementares sobre o projeto

**O projeto foi desenvolvido na linguagem python, vers√£o 3.11.1. N√£o foi utilizada nenhuma biblioteca al√©m da padr√£o que j√° vem instalado com o python**
